inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/PredicateName:
  Enabled: false
