require_relative 'movienga/version'
require_relative 'movienga/tmdb_parser'
require_relative 'movienga/imdb_parser'
require_relative 'movienga/movie_collection'
require_relative 'movienga/collection_enumerator'
require_relative 'movienga/cache'
require_relative 'movienga/cinemas/netflix'
require_relative 'movienga/cinemas/theatre'
